Refactoring

diff --git a/sql/deploy_database.yml b/sql/deploy_database.yml
--- a/sql/deploy_database.yml
+++ b/sql/deploy_database.yml
@@ -1,29 +1,4 @@
 steps:
-- ${{ if eq(parameters.useFirewall, true) }}:
-  - task: AzureCLI@2
-    displayName: 'Deploy ${{ parameters.databaseName }} to environment ${{ parameters.envName }}. Firewall rule created ${{ parameters.useFirewall }}'
-    env:
-      MSYS_NO_PATHCONV: 1
-    inputs:
-      azureSubscription: '${{ parameters.azureSubscription }}'
-      scriptType: bash
-      scriptLocation: inlineScript
-      inlineScript:  |
-        az sql server firewall-rule create -g ${{ parameters.resourceGroup }} -s ${{ parameters.serverName }} -n "${{ parameters.azureFirewallRule}}" --start-ip-address ${{ parameters.agentPublicIP }} --end-ip-address ${{ parameters.agentPublicIP }}
-        if [ "${{ parameters.skipProfile }}" == "False" ]
-        then
-          echo "Not use token"
-          ./tools/sqlpackage /Action:Publish -p:ScriptDatabaseCompatibility=true /SourceFile:"$(Pipeline.Workspace)/${{ parameters.artifactNamePrefix }}$(Build.DefinitionName).Dacpac/${{ parameters.databaseName }}.dacpac" /TargetConnectionString:"${{ parameters.connectionString }}" /Profile:"$(Pipeline.Workspace)/${{ parameters.artifactNamePrefix }}$(Build.DefinitionName).Dacpac/${{ parameters.databaseName }}.publish.xml" /v:"AzureDevOpsEnvironment=${{ parameters.env }}" /v:"AzureDevOpsEnvironmentName=$(Environment.Name)" /v:"AzureDevOpsBuildNumber=$(Build.BuildNumber)" /v:"AzureDevOpsRepositoryName=$(Build.Repository.Name)" /v:"AzureDevOpsSystem=${{ parameters.system }}" /v:"AzureDevOpsSuffix=${{ parameters.suffix }}" ${{ parameters.deployParameters }}
-          result=$?
-        else
-          echo "Not use token"
-          ./tools/sqlpackage /Action:Publish -p:ScriptDatabaseCompatibility=true /SourceFile:"$(Pipeline.Workspace)/${{ parameters.artifactNamePrefix }}$(Build.DefinitionName).Dacpac/${{ parameters.databaseName }}.dacpac" /TargetConnectionString:"${{ parameters.connectionString }}" /v:"AzureDevOpsEnvironment=${{ parameters.env }}" /v:"AzureDevOpsEnvironmentName=$(Environment.Name)" /v:"AzureDevOpsBuildNumber=$(Build.BuildNumber)" /v:"AzureDevOpsRepositoryName=$(Build.Repository.Name)" /v:"AzureDevOpsSystem=${{ parameters.system }}" /v:"AzureDevOpsSuffix=${{ parameters.suffix }}" ${{ parameters.deployParameters }}
-          result=$?
-        fi
-        az sql server firewall-rule delete -g ${{ parameters.resourceGroup }} -s ${{ parameters.serverName }} -n "${{ parameters.azureFirewallRule}}"
-        exit $result
-
-- ${{ if eq(parameters.useFirewall, false) }}:
   - task: AzureCLI@2
     displayName: 'Deploy ${{ parameters.databaseName }} to environment ${{ parameters.envName }}.'
     env:
@@ -33,16 +8,42 @@ steps:
       scriptType: bash
       scriptLocation: inlineScript
       inlineScript:  |
+        # Base command
+        cmd="./tools/sqlpackage"
+
+        # Common parameters
+        cmd+=" /Action:Publish -p:ScriptDatabaseCompatibility=true /SourceFile:\"$(Pipeline.Workspace)/${{ parameters.artifactNamePrefix }}$(Build.DefinitionName).Dacpac/${{ parameters.databaseName }}.dacpac\" /TargetConnectionString:\"${{ parameters.connectionString }}\" /v:\"AzureDevOpsEnvironment=${{ parameters.env }}\" /v:\"AzureDevOpsEnvironmentName=$(Environment.Name)\" /v:\"AzureDevOpsBuildNumber=$(Build.BuildNumber)\" /v:\"AzureDevOpsRepositoryName=$(Build.Repository.Name)\" /v:\"AzureDevOpsSystem=${{ parameters.system }}\" /v:\"AzureDevOpsSuffix=${{ parameters.suffix }}\" ${{ parameters.deployParameters }}"
+
+        # Check if Firewall is used
+        if [ "${{ parameters.useFirewall }}" = "True" ]; then
+          az sql server firewall-rule create -g ${{ parameters.resourceGroup }} -s ${{ parameters.serverName }} -n "${{ parameters.azureFirewallRule}}" --start-ip-address ${{ parameters.agentPublicIP }} --end-ip-address ${{ parameters.agentPublicIP }}
+          echo "Firewall rule created ${{ parameters.useFirewall }}"
+        fi
+
+        # Check Skip Profile
+        if [ "${{ parameters.skipProfile }}" = "False" ]; then
+          cmd+=" /Profile:\"$(Pipeline.Workspace)/${{ parameters.artifactNamePrefix }}$(Build.DefinitionName).Dacpac/${{ parameters.databaseName }}.publish.xml\""
+          echo "Use profile"
+        fi
+
+        # Check useToken
         if [ "${{ parameters.useToken }}" = "True" ]; then
           token=$(az account get-access-token --resource https://database.windows.net/ --query accessToken --output tsv)
-          ./tools/sqlpackage /Action:Publish -p:ScriptDatabaseCompatibility=true /at:$token /SourceFile:"$(Pipeline.Workspace)/${{ parameters.artifactNamePrefix }}$(Build.DefinitionName).Dacpac/${{ parameters.databaseName }}.dacpac" /TargetConnectionString:"${{ parameters.connectionString }}" /Profile:"$(Pipeline.Workspace)/${{ parameters.artifactNamePrefix }}$(Build.DefinitionName).Dacpac/${{ parameters.databaseName }}.publish.xml" /v:"AzureDevOpsEnvironment=${{ parameters.env }}" /v:"AzureDevOpsEnvironmentName=$(Environment.Name)" /v:"AzureDevOpsBuildNumber=$(Build.BuildNumber)" /v:"AzureDevOpsRepositoryName=$(Build.Repository.Name)" /v:"AzureDevOpsSystem=${{ parameters.system }}" /v:"AzureDevOpsSuffix=${{ parameters.suffix }}" ${{ parameters.deployParameters }}
-          result=$?
-        elif [ "${{ parameters.skipProfile }}" == "False" ]; then
-          ./tools/sqlpackage /Action:Publish -p:ScriptDatabaseCompatibility=true /SourceFile:"$(Pipeline.Workspace)/${{ parameters.artifactNamePrefix }}$(Build.DefinitionName).Dacpac/${{ parameters.databaseName }}.dacpac" /TargetConnectionString:"${{ parameters.connectionString }}" /Profile:"$(Pipeline.Workspace)/${{ parameters.artifactNamePrefix }}$(Build.DefinitionName).Dacpac/${{ parameters.databaseName }}.publish.xml" /v:"AzureDevOpsEnvironment=${{ parameters.env }}" /v:"AzureDevOpsEnvironmentName=$(Environment.Name)" /v:"AzureDevOpsBuildNumber=$(Build.BuildNumber)" /v:"AzureDevOpsRepositoryName=$(Build.Repository.Name)" /v:"AzureDevOpsSystem=${{ parameters.system }}" /v:"AzureDevOpsSuffix=${{ parameters.suffix }}" ${{ parameters.deployParameters }}
-          result=$?
-        else
-          ./tools/sqlpackage /Action:Publish -p:ScriptDatabaseCompatibility=true /SourceFile:"$(Pipeline.Workspace)/${{ parameters.artifactNamePrefix }}$(Build.DefinitionName).Dacpac/${{ parameters.databaseName }}.dacpac" /TargetConnectionString:"${{ parameters.connectionString }}" /v:"AzureDevOpsEnvironment=${{ parameters.env }}" /v:"AzureDevOpsEnvironmentName=$(Environment.Name)" /v:"AzureDevOpsBuildNumber=$(Build.BuildNumber)" /v:"AzureDevOpsRepositoryName=$(Build.Repository.Name)" /v:"AzureDevOpsSystem=${{ parameters.system }}" /v:"AzureDevOpsSuffix=${{ parameters.suffix }}" ${{ parameters.deployParameters }}
-          result=$?
+          cmd+=" /at:$token"
+          echo "Use token"
         fi
+
+        # Execute the command
+        eval $cmd
+
+        # Capture the exit code of eval
+        result=$?
+
+        # Remove Firewall rule if Firewall is in use
+        if [ "${{ parameters.useFirewall }}" = "True" ]; then
+          az sql server firewall-rule delete -g ${{ parameters.resourceGroup }} -s ${{ parameters.serverName }} -n "${{ parameters.azureFirewallRule}}"
+          echo "Firewall rule removed ${{ parameters.useFirewall }}"
+        fi
+
         exit $result
        
